main/main/Controllers/NewPageController.cs
using algorytm;
using Gradient;
using GTOAnamespace;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using TSFDE_fractional_boundary_condition;
using ZadanieAA;
using static iText.IO.Image.Jpeg2000ImageData;


    public class NewPageController : Controller
    {
        public IActionResult Index()
        {
            // Utwórz instancję algorytmu ABC
            var abcAlgorithm = ABC.GetInstance();
            // Pobierz ParamsInfo z ABC
            var paramsInfoList = new List<ParamInfo[]> { abcAlgorithm.ParamsInfo };

            // Dodaj informacje o parametrach z innych algorytmów (dla przykładu Gradient)
            var gradientAlgorithm = GradientDescent.GetInstance(); // Zakładając, że masz odpowiednią implementację dla GradientDescent
            paramsInfoList.Add(gradientAlgorithm.ParamsInfo);

            var gotaAlgorithm = GTOA.GetInstance();
            paramsInfoList.Add(gotaAlgorithm.ParamsInfo);
            // Możesz dodać informacje o parametrach z innych algorytmów, jeśli są dostępne

            // Przekaż listę z danymi ParamsInfo do widoku
            ViewBag.ParamsInfoList = paramsInfoList;

            return View();
        }
    public IActionResult SomeAction()
    {
        // Przekierowanie na nową stronę
        return RedirectToAction("Index", "Settings");
    }
    public IActionResult SomeActionGTOA()
    {
        // Przekierowanie na nową stronę
        return RedirectToAction("Index", "SettingsGTOA");
    }
    public IActionResult SomeActionGradient()
    {
        // Przekierowanie na nową stronę
        return RedirectToAction("Index", "SettingsGradient");
    }
    [HttpPost]
        public JsonResult RunOptimization([FromBody] OptimizationParameters optimizationParameters)
        {
            // Dostosuj logikę optymalizacji używając parametrów z modelu
            TSFDE_fractional_boundary tsfde_inv = new TSFDE_fractional_boundary();
        ObjectiveFunction of = new ObjectiveFunction();

        //Console.Write($"dane parametru {optimizationParameters.SelectedAlgorithms}");
        // Ustaw funkcję celu na podstawie wartości przekazanej z formularza
        FitnessFunction fitnessFunctionDelegate = null;
            string funcName = null;

            var selectedFunction = optimizationParameters.ObjectiveFunction;
            //Console.Write($"jebane funkcje sele{selectedFunction[1]}");
            var results = new List<AlgorithmResult>();
   
        //Console.WriteLine(function);
        switch (selectedFunction[0])
            {
                case "SphereFunction":
                    fitnessFunctionDelegate = SphereFunction.Evaluate;
                    funcName = "SphereFunction";
                    break;
                case "RosenbrockFunction":
                    fitnessFunctionDelegate = RosenbrockFunction.Evaluate;
                    funcName = "RosenbrockFunction";
                    break;
                case "RastriginFunction":
                    fitnessFunctionDelegate = RastriginFunction.Evaluate;
                    funcName = "RastriginFunction";
                    break;
                case "tsfde_inv":
                    fitnessFunctionDelegate = tsfde_inv.fintnessFunction;
                    funcName = "tsfde_inv";
                optimizationParameters.Parameters[0] = 7;
                break;
                case "przyklad":
                    fitnessFunctionDelegate = of.FunkcjaCelu.Wartosc;
                    funcName = "przyklad";
                break;
            default:
                    fitnessFunctionDelegate = RastriginFunction.Evaluate;
                    funcName = "RastriginFunction";
                    break;
            }
            var selectedAlgorithms = optimizationParameters.SelectedAlgorithms; // Pobierz zaznaczone algorytmy





            foreach (var algorithm in selectedAlgorithms)
            {
                IOptimizationAlgorith optimizationAlgorithm = null;
            Console.WriteLine(algorithm);
                switch (algorithm)
                {
                    case "ABC":
                        optimizationAlgorithm = ABC.GetInstance();
                        using(StreamReader reader = new StreamReader("D:\\Kod\\c#\\interfejs\\settings\\abc.txt"))
                        {
                            // Wczytaj dane z pliku, podziel je na elementy i przekonwertuj na liczby
                            double[] FileNumbers = reader.ReadLine()
                                .Split(',')
                                 .Select(s => double.Parse(s, CultureInfo.InvariantCulture))
                                .ToArray();

                            // Dołącz dane z pliku do tablicy parameters
                            optimizationParameters.Parameters = optimizationParameters.Parameters.Concat(FileNumbers).ToArray();
                       

                    }
                        break;
                    case "Gradient":
                        optimizationAlgorithm = GradientDescent.GetInstance();
                        using (StreamReader reader = new StreamReader("D:\\Kod\\c#\\interfejs\\settings\\gradient.txt"))
                        {
                            // Wczytaj dane z pliku, podziel je na elementy i przekonwertuj na liczby
                            double[] FileNumbers = reader.ReadLine()
                                .Split(',')
                                .Select(s => double.Parse(s, CultureInfo.InvariantCulture))
                                .ToArray();

                            // Dołącz dane z pliku do tablicy parameters
                            optimizationParameters.Parameters = optimizationParameters.Parameters.Concat(FileNumbers).ToArray();
                        }
                        break;
                    case "GTOA":
                        optimizationAlgorithm = GTOA.GetInstance();
                        using (StreamReader reader = new StreamReader("D:\\Kod\\c#\\interfejs\\settings\\gtoa.txt"))
                        {
                            // Wczytaj dane z pliku, podziel je na elementy i przekonwertuj na liczby
                            double[] FileNumbers = reader.ReadLine()
                                .Split(',')
                                .Select(s => double.Parse(s, CultureInfo.InvariantCulture))
                                .ToArray();

                            // Dołącz dane z pliku do tablicy parameters
                            optimizationParameters.Parameters = optimizationParameters.Parameters.Concat(FileNumbers).ToArray();
                        }
                        break;

                    default:

                        break;
                }
                if (optimizationAlgorithm != null)
                {

                    var reportGenerator = new ReportGenerator(optimizationAlgorithm);
                    DateTime currentDate = DateTime.Now;
                    string timestamp = DateTime.Now.ToString("dd_MM_yyyy_HH_mm_ss");
                    // Inicjalizacja domain jako nowej instancji listy list
                    optimizationParameters.domain = new List<List<double>>();

                    // Dodawanie dwóch pustych list do domain (jeśli wymaga tego struktura)
                    optimizationParameters.domain.Add(new List<double>());
                    optimizationParameters.domain.Add(new List<double>());
                    if (fitnessFunctionDelegate == SphereFunction.Evaluate)
                    {
                        for (int i = 0; i < optimizationParameters.Parameters[0]; i++)
                        {
                            optimizationParameters.domain[0].Add(-10);
                            optimizationParameters.domain[1].Add(10);
                        }
                    }
                    if (fitnessFunctionDelegate == RosenbrockFunction.Evaluate)
                    {
                        for (int i = 0; i < optimizationParameters.Parameters[0]; i++)
                        {
                            optimizationParameters.domain[0].Add(-10);
                            optimizationParameters.domain[1].Add(10);
                        }
                    }
                    if (fitnessFunctionDelegate == RastriginFunction.Evaluate)
                    {
                        for (int i = 0; i < optimizationParameters.Parameters[0]; i++)
                        {
                            optimizationParameters.domain[0].Add(-5.12);
                            optimizationParameters.domain[1].Add(5.12);
                        }
                    }
                    if (fitnessFunctionDelegate == tsfde_inv.fintnessFunction)
                    {
                        double[] a = { 0.1, 1.1, 1.0, -70.0, 250.0, -30.0, 50.0 };
                        double[] b = { 0.9, 1.9, 5.0, -20.0, 450.0, -10.0, 250.0 };

                        optimizationParameters.domain[0].AddRange(a);
                        optimizationParameters.domain[1].AddRange(b);
                    }
                if (fitnessFunctionDelegate == of.FunkcjaCelu.Wartosc)
                {
                    for (int i = 0; i < optimizationParameters.Parameters[0]; i++)
                    {
                        optimizationParameters.domain[0].Add(0.5);
                        optimizationParameters.domain[1].Add(1.5);
                    }
                }
                optimizationAlgorithm.Solve(fitnessFunctionDelegate, optimizationParameters.domain, optimizationParameters.Parameters);
                    reportGenerator.SetParameters(optimizationParameters.Parameters, funcName);
                    reportGenerator.GenerateReport($"D:\\Kod\\c#\\interfejs\\RAPORTY\\raport_{timestamp}.pdf");

                    results.Add(new AlgorithmResult
                    {

                        Algorithm = algorithm,
                        Fitness = optimizationAlgorithm.FBest,

main/main/Views/NewPage/Index.cshtml
@{
    ViewData["Title"] = "Optimization";
}

<h1 class="text-2xl mb-3 font-bold">@ViewData["Title"]</h1>
<a asp-action="SomeAction" asp-controller="NewPage">settingsABC</a>
<a asp-action="SomeActionGTOA" asp-controller="NewPage">settingsGTOA</a>
<a asp-action="SomeActionGradient" asp-controller="NewPage">settingsGradient</a>
<div data-badges class="flex flex-wrap gap-1">
    <div class="badge badge-info gap-2">
        <svg data-badge-delete="ABC" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
        ABC
    </div>
</div>
<div class="flex justify-between mb-2">
    <label for="optimizationAlgorithm" class="flex items-center">Optimization Algorithm:</label>
    <select id="selectedAlgorithms" class="select select-bordered w-full max-w-xs" data-algorithms data-objfun>
        <option value="ABC" selected>ABC</option>
        <option value="Gradient">Gradient</option>
        <option value="GTOA">GTOA</option>
    </select>
</div>

<div>
    <form id="abcForm" action="/NewPage/RunOptimization" method="post" data-form="ABC">
        <div class="flex justify-between mb-2">
            <label class="flex items-center">Dimensions:</label>
            <input type="text" id="dimensions" name="dimensions" required placeholder="Type here" class="input input-bordered w-full max-w-xs" />
        </div>
        <div class="flex justify-between mb-2">
            <label class="flex items-center">generations:</label>
            <input type="text" id="generations" name="generations" required placeholder="Type here" class="input input-bordered w-full max-w-xs" />
        </div>

        <div class="flex justify-between mb-2">
            <label for="objectiveFunction" class="flex items-center">Objective Function:</label>
            <select id="objectiveFunction" class="select select-bordered w-full max-w-xs">
                <option selected value="SphereFunction">Sphere Function</option>
                <option value="RosenbrockFunction">Rosenbrock Function</option>
                <option value="RastriginFunction">Rastrigin Function</option>
                <option value="tsfde_inv">tsfde_inv</option>
                <option value="przyklad">przyklad</option>
            </select>
        </div>


        <button type="submit" id="abcSubmitButton" class="btn mb-3">Run Optimization</button>
    </form>

</div>

@* @using (Html.BeginForm("RunOptimization", "Home", FormMethod.Post, new { id = "gradientForm" }))
{
    <div>
        @foreach (var paramInfo in ViewBag.ParamsInfoList[1])
        {

            <div>
                <label>@paramInfo.Name:</label>
                <input type="text" id="@paramInfo.Name" name="@paramInfo.Name" />
            </div>
        }
    </div>

    <label for="objectiveFunction">Objective Function:</label>
    <select id="objectiveFunction">
        <option value="SphereFunction">Sphere Function</option>
        <option value="RosenbrockFunction">Rosenbrock Function</option>
        <option value="RastriginFunction">Rastrigin Function</option>
    </select>

    <br>

    <button type="submit" id="gradientSubmitButton">Run Gradient Optimization</button>
} *@

<div id="resultContainer">
</div>
<div id="resultsContainer"></div>

@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        const algorithms = document.querySelector('[data-algorithms]');
        const forms = document.querySelectorAll("[data-form]");

        // algorithms.addEventListener('change', (e) => {
        //     const selectedAlgorithm = e.target.value;
        //     const selectedForm = document.querySelector([data-form="${selectedAlgorithm}"]);

        //     forms.forEach(el => {
        //         if (!el.classList.contains('hidden')) {
        //             el.classList.add('hidden')
        //         }
        //     });

        //     selectedForm.classList.remove("hidden")

        // })

        const badgesDom = document.querySelector('[data-badges]');
        const badges = ['ABC'];
        const objFunArr = document.querySelectorAll('[data-objfun]');

        const handleDelete = (e) => {
            console.log(badges)
            badges.splice(badges.indexOf(e.target.dataset.badgeDelete), 1);
            console.log(badges)

            badgesDom.innerHTML = `
                                                ${badges.map(badge => `
                                                    <div class="badge badge-info gap-2">
                                                        <svg data-badge-delete="${badge}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                                                        ${badge}
                                                    </div>
                                                `).join('')}
                                            `

        }
        document.querySelectorAll('[data-badge-delete]').forEach(deleteEl => deleteEl.addEventListener('click', handleDelete))
        objFunArr.forEach(objFun => objFun.addEventListener('change', e => {

            if (badges.indexOf(e.target.value) === -1) {
                badges.push(e.target.value)
            }

            badgesDom.innerHTML = `
                                ${badges.map(badge => `
                                    <div class="badge badge-info gap-2">
                                        <svg data-badge-delete="${badge}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-4 h-4 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                                        ${badge}
                                    </div>
                                `).join('')}
                            `

            document.querySelectorAll('[data-badge-delete]').forEach(deleteEl => deleteEl.addEventListener('click', handleDelete))
        }))

        $(document).ready(function () {
            const html = document.querySelector("html").dataset.theme = 'light'
            // Obsługa formularza ABC
            $("#abcForm").submit(function (event) {
                event.preventDefault();

                var optimizationParameters = {
                    parameters: [],
                    objectiveFunction: [],
                    selectedAlgorithms: badges
                };

                optimizationParameters.objectiveFunction.push($("#objectiveFunction").val());
                optimizationParameters.parameters.push(parseFloat($("#dimensions").val()));
                optimizationParameters.parameters.push(parseFloat($("#generations").val()));
                sendOptimizationRequest(optimizationParameters);
            });


            function sendOptimizationRequest(parameters) {
                $.ajax({
                    url: "/NewPage/RunOptimization",
                    type: "POST",
                    contentType: "application/json",
                    data: JSON.stringify(parameters),
                    success: function (data) {
                        // Usuń poprzednie wyniki
                        $("#resultsContainer").empty();
                        // Obsłuż wyniki dla każdego algorytmu

                        data.forEach(function (result) {
                            var resultElement = $("<div>");
                            resultElement.append("<p>Algorithm: " + result.algorithm + "</p>");
                            resultElement.append("<p>Best Fitness: " + result.fitness + "</p>");
                            resultElement.append("<p>Best Solution: " + result.solution.join(", ") + "</p>");

                            $("#resultsContainer").append(resultElement);
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            }
        });
    </script>
}